sudo: false
language: python
cache: pip
python:
    - "3.5"
    - "3.6"
addons:
    postgresql: 9.5
    apt:
        packages:
            - postgresql-9.5-postgis-2.3
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravisCI"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - AZUREAD_AUTHORITY="https://login.microsoftonline.com/thisisnotarealazureaudauthorityurl"
install:
    - psql -U postgres -c "create extension postgis"
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - coverage run --source="." manage.py test
after_success:
    - coveralls
