[tool.poetry]
name = "authome"
version = "1.0.1"
description = "HTTP service for single sign-on session tracking"
authors = ["ASI <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
Django = "2.1.5"
django-confy = "1.0.4"
django-ipware = "2.1.0"
social-auth-app-django = "3.1.0"
social-auth-core = "3.0.0"
psycopg2-binary = "2.7.7"
gevent = "1.4.0"
gunicorn = "19.9.0"
adal = "1.2.4"

[tool.poetry.dev-dependencies]
ipython = "^7.18.1"
coverage = "^5.3"
coveralls = "^2.1.2"
mock = "^4.0.2"
ipdb = "^0.13.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
