#!/bin/bash
TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
export TEST_RUNNER
export CACHE_SERVER="redis://@127.0.0.1:6370/0"
export CACHE_SERVER_OPTIONS="cluster=False"
#source venv/bin/activate && python manage.py test authome --keepdb
export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testrequestheaders.py"
