#!/bin/bash
if [[ "$1" == "" ]] 
then
    backend="false"
elif [[ "$1" == "true" ]] 
then
    backend="true"
else
    backend="false"
fi

TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
export TEST_RUNNER
#source venv/bin/activate && python manage.py test authome --keepdb

if [[ "$backend" == "true" ]] 
then
    export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testmonitoring.py" > ./logs/testmonitoring.log 2>&1  &
else
    export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testmonitoring.py"
fi
