#!/bin/bash
TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
export TEST_RUNNER
export CACHE_SERVER="redis://@127.0.0.1:6380/0;redis://@127.0.0.1:6381/0;redis://@127.0.0.1:6382/0;redis://@127.0.0.1:6383/0;redis://@127.0.0.1:6384/0;redis://@127.0.0.1:6385/0;"
export CACHE_SERVER_OPTIONS=cluster_error_retry_attempts=3,require_full_coverage=False,auto_failover=True
#source venv/bin/activate && python manage.py test authome --keepdb
export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testrediscluster.py"
