#!/bin/bash
TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
export TEST_RUNNER
#source venv/bin/activate && python manage.py test authome --keepdb
export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testrequestheaders.py"
