#!/bin/bash
#source venv/bin/activate && python manage.py test authome --keepdb
TEST_RUNNER=authome.testrunners.NoDatabaseTestRunner
export TEST_RUNNER
export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="testcluster.py"
