#!/bin/bash
#source venv/bin/activate && python manage.py test authome --keepdb
source .env.auth01
export IGNORE_LOADING_ERROR=True;export CACHE_SERVER CACHE_SERVER_OPTIONS AUTH2_CLUSTERID AUTH2_CLUSTER_ENDPOINT DEFAULT_AUTH2_CLUSTER ; poetry run python manage.py test authome --keepdb --pattern="test_*.py"
#export IGNORE_LOADING_ERROR=True;export CACHE_SERVER CACHE_SERVER_OPTIONS AUTH2_CLUSTERID AUTH2_CLUSTER_ENDPOINT DEFAULT_AUTH2_CLUSTER ; poetry run python manage.py test authome --keepdb --pattern="test_tcontrol.py"
