#!/bin/bash
#source venv/bin/activate && python manage.py test authome --keepdb
export IGNORE_LOADING_ERROR=True; poetry run python manage.py test authome --keepdb --pattern="test_*.py"
#export IGNORE_LOADING_ERROR=True ; poetry run python manage.py test authome --keepdb --pattern="test_authorization.py"
