# Generated by Django 2.2.16 on 2020-10-29 04:31

import authome.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('excluded_paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('sortkey', models.CharField(editable=False, max_length=96)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('user', 'domain')},
            },
            bases=(authome.models.DbObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('users', authome.models._ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('excluded_users', authome.models._ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authome.UserGroup')),
            ],
            options={
                'unique_together': {('users', 'excluded_users')},
            },
            bases=(authome.models.DbObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserGroupAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('excluded_paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('sortkey', models.CharField(editable=False, max_length=96)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authome.UserGroup')),
            ],
            options={
                'unique_together': {('usergroup', 'domain')},
            },
            bases=(authome.models.DbObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enabled', models.BooleanField(default=False, editable=False)),
                ('token', models.CharField(editable=False, max_length=128, null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('expired', models.DateField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
