# Generated by Django 2.2.16 on 2020-10-22 07:13

import authome.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('users', authome.models._ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('excluded_users', authome.models._ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authome.UserGroup')),
            ],
            options={
                'unique_together': {('users', 'excluded_users')},
            },
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('excluded_paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('sortkey', models.CharField(editable=False, max_length=96)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroupRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('excluded_paths', authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('sortkey', models.CharField(editable=False, max_length=96)),
                ('modified', models.DateTimeField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authome.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
