# Generated by Django 2.2.16 on 2020-10-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0002_usergroup_usergrouprequests_userrequests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergrouprequests',
            unique_together={('usergroup', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='userrequests',
            unique_together={('user', 'domain')},
        ),
    ]
