# Generated by Django 2.2.16 on 2020-11-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0002_auto_20201029_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
