# Generated by Django 2.2.16 on 2020-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0002_auto_20201203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
