# Generated by Django 2.2.16 on 2020-10-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0003_auto_20201023_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
