# Generated by Django 2.2.16 on 2021-02-08 00:24

import authome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0003_auto_20201203_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableUserflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='*', help_text="Global setting if domain is '*'; otherwise is individual domain settings", max_length=128, unique=True)),
                ('fixed', models.CharField(help_text='The only user flow used by this domain if configured', max_length=64, null=True)),
                ('default', models.CharField(help_text='The default user flow used by this domain', max_length=64, null=True)),
                ('email_signup', models.CharField(help_text='The email signup user flow', max_length=64, null=True)),
                ('email', models.CharField(help_text='The email signup and signin user flow', max_length=64, null=True)),
                ('profile_edit', models.CharField(help_text='The user profile edit user flow', max_length=64, null=True)),
                ('password_reset', models.CharField(help_text='The user password reset user flow', max_length=64, null=True)),
                ('email_enabled', models.BooleanField(default=True, editable=False, help_text='Enable/Disable the email singin for this domain')),
                ('page_layout', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(authome.models.DbObjectMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='identityprovider',
            name='domains',
        ),
    ]
