# Generated by Django 2.2.16 on 2020-11-11 23:58

import authome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0004_auto_20201106_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au  \n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=64),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='excluded_paths',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text="\nList all possible paths separated by new line character.\nThe following lists all valid options in the checking order\n    1. All path      : *\n    2. Prefix path   : the paths except All path, regex path and exact path. For example /admin\n    3. Regex path    : A regex string starts with '^'. For example ^.*/add$\n    4. Exact path  : Starts with '=', represents a single request path . For example =/register\n", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='paths',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text="\nList all possible paths separated by new line character.\nThe following lists all valid options in the checking order\n    1. All path      : *\n    2. Prefix path   : the paths except All path, regex path and exact path. For example /admin\n    3. Regex path    : A regex string starts with '^'. For example ^.*/add$\n    4. Exact path  : Starts with '=', represents a single request path . For example =/register\n", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='excluded_users',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=64), blank=True, help_text="\nList all possible user emails in this group separated by new line character.\nThe following lists all valid options in the checking order\n    1. All emails    : *\n    2. Domain emails : starts with '@', followed by email domain. For example@dbca.wa.gov.au\n    3. Email pattern : '*' represents any strings. For example test_*@dbca.wa.gov.au\n    4. User email    : represent a single user email, For example test_user01@dbca.wa.gov.au\n", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=64), help_text="\nList all possible user emails in this group separated by new line character.\nThe following lists all valid options in the checking order\n    1. All emails    : *\n    2. Domain emails : starts with '@', followed by email domain. For example@dbca.wa.gov.au\n    3. Email pattern : '*' represents any strings. For example test_*@dbca.wa.gov.au\n    4. User email    : represent a single user email, For example test_user01@dbca.wa.gov.au\n", size=None),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au  \n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=64),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='excluded_paths',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text="\nList all possible paths separated by new line character.\nThe following lists all valid options in the checking order\n    1. All path      : *\n    2. Prefix path   : the paths except All path, regex path and exact path. For example /admin\n    3. Regex path    : A regex string starts with '^'. For example ^.*/add$\n    4. Exact path  : Starts with '=', represents a single request path . For example =/register\n", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='paths',
            field=authome.models._ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text="\nList all possible paths separated by new line character.\nThe following lists all valid options in the checking order\n    1. All path      : *\n    2. Prefix path   : the paths except All path, regex path and exact path. For example /admin\n    3. Regex path    : A regex string starts with '^'. For example ^.*/add$\n    4. Exact path  : Starts with '=', represents a single request path . For example =/register\n", null=True, size=None),
        ),
    ]
