# Generated by Django 2.2.16 on 2020-10-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authome', '0004_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enabled', models.BooleanField(default=False, editable=False)),
                ('token', models.CharField(editable=False, max_length=128, null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('expired', models.DateField(editable=False, null=True)),
            ],
        ),
    ]
