# Generated by Django 2.2.16 on 2020-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0005_auto_20201112_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('idp', models.CharField(editable=False, max_length=256, unique=True)),
                ('userflow', models.CharField(blank=True, max_length=64, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
