# Generated by Django 3.1.6 on 2021-02-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0006_user_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizableuserflow',
            name='extracss',
            field=models.TextField(blank=True, null=True),
        ),
    ]
