# Generated by Django 2.2.16 on 2020-11-19 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0006_identityprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='identity_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authome.IdentityProvider'),
        ),
    ]
