# Generated by Django 2.2.16 on 2020-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0007_usergroup_identity_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='logout_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
