# Generated by Django 3.1.6 on 2021-02-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0007_customizableuserflow_extracss'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizableuserflow',
            name='verifyemail_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizableuserflow',
            name='verifyemail_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customizableuserflow',
            name='verifyemail_subject',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
