# Generated by Django 3.1.6 on 2021-02-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0009_auto_20210224_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(editable=False, max_length=64)),
                ('idp', models.CharField(editable=False, max_length=256)),
                ('secret_key', models.CharField(editable=False, max_length=128)),
                ('timestep', models.PositiveSmallIntegerField(editable=False)),
                ('prefix', models.CharField(editable=False, max_length=64)),
                ('issuer', models.CharField(editable=False, max_length=64)),
                ('algorithm', models.CharField(editable=False, max_length=32)),
                ('digits', models.PositiveSmallIntegerField(editable=False)),
                ('last_verified_code', models.CharField(editable=False, max_length=16, null=True)),
                ('last_vefified', models.DateTimeField(editable=False)),
                ('created', models.DateTimeField(editable=False)),
            ],
            options={
                'unique_together': {('email', 'idp')},
            },
        ),
    ]
