# Generated by Django 3.1.6 on 2021-02-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0010_usertotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertotp',
            old_name='last_vefified',
            new_name='last_verified',
        ),
    ]
