# Generated by Django 3.1.6 on 2021-02-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0011_auto_20210226_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotp',
            name='last_verified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
