# Generated by Django 3.1.6 on 2021-03-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0012_auto_20210226_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotp',
            name='name',
            field=models.CharField(default='test', editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
