# Generated by Django 3.1.6 on 2021-03-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0013_usertotp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizableuserflow',
            name='email_enabled',
        ),
    ]
