# Generated by Django 3.1.6 on 2021-03-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0014_remove_customizableuserflow_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizableuserflow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authome.customizableuserflow'),
        ),
    ]
