# Generated by Django 3.1.6 on 2021-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0015_customizableuserflow_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizableuserflow',
            name='mfa_reset',
            field=models.CharField(blank=True, help_text='The mfa reset user flow', max_length=64, null=True),
        ),
    ]
