# Generated by Django 3.1.6 on 2021-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0016_customizableuserflow_mfa_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizableuserflow',
            name='parent',
        ),
        migrations.AddField(
            model_name='customizableuserflow',
            name='sortkey',
            field=models.CharField(default=99, editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customizableuserflow',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. Only single domain can config path and excluded path\n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. Only single domain can config path and excluded path\n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='sortkey',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. Only single domain can config path and excluded path\n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='sortkey',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
