# Generated by Django 3.1.6 on 2021-04-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0017_auto_20210325_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='logout_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manually Logout'), (2, 'Auto Logout')], null=True),
        ),
    ]
