# Generated by Django 3.1.6 on 2021-04-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0018_identityprovider_logout_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='logout_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manually Logout'), (2, 'Auto Logout'), (3, 'Auto Logout With Popup Window')], null=True),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
