# Generated by Django 3.1.6 on 2021-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0020_auto_20210520_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'System User', 'verbose_name_plural': '       System Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '        User'},
        ),
        migrations.AlterModelOptions(
            name='useraccesstoken',
            options={'verbose_name_plural': '      Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': '       User Access Tokens'},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='groupid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='grouppath',
            field=models.CharField(editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customizableuserflow',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. \n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
        migrations.AlterField(
            model_name='userauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. \n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
        migrations.AlterField(
            model_name='usergroupauthorization',
            name='domain',
            field=models.CharField(help_text='\nA domain or domain pattern \nThe following lists all valid options in the checking order\n    1. Single Domain : Represent a single domain. For example oim.dbca.wa.gov.au. \n    2. Regex Domain  : \'*" represents any strings. For example  pbs*dbca.wa.gov.au\n    3. Suffix Domain : Starts with \'.\' followed by a domain. For example .dbca.wa.gov.au\n    4. All Domain    : \'*\'\n', max_length=128),
        ),
    ]
