# Generated by Django 3.1.6 on 2021-06-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0022_auto_20210614_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usergroup',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='grouppath',
        ),
    ]
