# Generated by Django 3.1.6 on 2021-06-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0023_auto_20210618_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupid',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
