# Generated by Django 3.1.6 on 2022-02-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0026_auto_20220221_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizableuserflow',
            name='email',
        ),
    ]
