# Generated by Django 3.1.6 on 2022-03-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0027_remove_customizableuserflow_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizableuserflow',
            name='profile_edit',
        ),
    ]
