# Generated by Django 3.1.6 on 2022-03-16 01:56

from django.db import migrations, models
from authome.models import UserTOTP


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0028_remove_customizableuserflow_profile_edit'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM {} WHERE idp != 'local'".format(UserTOTP._meta.db_table)),
        migrations.AlterField(
            model_name='usertotp',
            name='email',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usertotp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usertotp',
            name='idp',
        ),
    ]
