# Generated by Django 3.1.6 on 2022-03-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0029_auto_20220316_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotp',
            name='secret_key',
            field=models.CharField(editable=False, max_length=512),
        ),
    ]
