# Generated by Django 3.2.12 on 2022-05-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0030_auto_20220317_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizableuserflow',
            name='sortkey',
            field=models.CharField(help_text="A sorting string consisted with a 2 digitals and string separated by ':', the sorting string is auto generated if the digitals is in [99, 10, 60, 40]", max_length=128),
        ),
    ]
