# Generated by Django 3.2.12 on 2022-06-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0031_alter_customizableuserflow_sortkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='identity_provider',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('idp__exact', 'auth_email_verify'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='authome.identityprovider'),
        ),
    ]
