# Generated by Django 3.2.12 on 2022-06-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0033_auto_20220613_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth2Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterid', models.CharField(max_length=32, unique=True)),
                ('endpoint', models.CharField(max_length=512)),
                ('default', models.BooleanField(default=False, editable=False)),
                ('usergroup_lastrefreshed', models.DateTimeField(editable=False)),
                ('usergroupauthorization_lastrefreshed', models.DateTimeField(editable=False)),
                ('userflow_lastrefreshed', models.DateTimeField(editable=False)),
                ('idp_lastrefreshed', models.DateTimeField(editable=False)),
                ('last_heartbeat', models.DateTimeField(editable=False)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'auth2 clusters',
            },
        ),
        migrations.AlterModelOptions(
            name='customizableuserflow',
            options={'verbose_name_plural': '   Customizable userflows'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'User', 'verbose_name_plural': '         Users'},
        ),
        migrations.AlterModelOptions(
            name='normalusertoken',
            options={'verbose_name': 'System User', 'verbose_name_plural': '        User Tokens'},
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'System User', 'verbose_name_plural': '       System Users'},
        ),
        migrations.AlterModelOptions(
            name='systemusertoken',
            options={'verbose_name': 'System User', 'verbose_name_plural': '      System User Tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '         Users'},
        ),
        migrations.AlterModelOptions(
            name='userauthorization',
            options={'verbose_name_plural': '  User Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name_plural': '     User Groups'},
        ),
        migrations.AlterModelOptions(
            name='usergroupauthorization',
            options={'verbose_name_plural': '    User Group Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='usertotp',
            options={'verbose_name_plural': ' User totps'},
        ),
    ]
