# Generated by Django 3.2.12 on 2022-09-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0038_auto_20220908_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debuglog',
            old_name='source_session_key',
            new_name='source_session_cookie',
        ),
        migrations.RenameField(
            model_name='debuglog',
            old_name='target_session_key',
            new_name='target_session_cookie',
        ),
        migrations.AlterField(
            model_name='debuglog',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Create cookie'), (11, 'Update cookie'), (12, 'Delete cookie'), (20, 'Upgrade session'), (21, 'Upgrade upgraded session'), (22, 'Upgrade non-exist session'), (30, 'Migrate session'), (31, 'Migrate migrated session'), (32, 'Migrate non-exist session'), (40, 'Move previous session'), (41, 'Move moved previous session'), (42, 'Move non-exist previous session'), (50, 'Auth2 Cluster Not Available'), (123, 'Upgrade non-exist upgraded session'), (133, 'Migrate non-exist migrated session'), (143, 'Move non-exist moved previous session'), (201, 'LB key not match'), (202, 'Domain not match'), (210, 'Session cookie hacked'), (200, 'Error')], default=10),
        ),
    ]
