# Generated by Django 3.2.12 on 2022-09-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0039_auto_20220912_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debuglog',
            old_name='base_session_key',
            new_name='session_key',
        ),
    ]
