# Generated by Django 3.2.12 on 2023-05-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0041_alter_debuglog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizableuserflow',
            name='relogin_url',
            field=models.CharField(blank=True, help_text='A link used in default signout page to let user relogin to the system after signout from sso, ignore this setting if signedout_url is configured.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customizableuserflow',
            name='signedout_url',
            field=models.CharField(blank=True, help_text='Redirect to this url after signout from sso', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customizableuserflow',
            name='signout_body',
            field=models.TextField(blank=True, help_text='The body template used in the signedout page', null=True),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='secretkey_expireat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
