# Generated by Django 3.2.12 on 2023-05-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0042_auto_20230509_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizableuserflow',
            name='relogin_url',
            field=models.CharField(blank=True, help_text='A link can be used in signed out page to let user relogin to the system after signout from sso.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customizableuserflow',
            name='signedout_url',
            field=models.CharField(blank=True, help_text='Redirect to this url after sign out from sso', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customizableuserflow',
            name='signout_body',
            field=models.TextField(blank=True, help_text='The body template used in the signed out page', null=True),
        ),
    ]
