# Generated by Django 4.2.15 on 2024-08-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0044_alter_usergroup_excluded_users_alter_usergroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
