# Generated by Django 4.2.15 on 2024-08-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0045_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
