# Generated by Django 4.2.16 on 2024-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0046_alter_user_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth2cluster',
            options={'verbose_name_plural': '       Auth2 Clusters'},
        ),
        migrations.AlterModelOptions(
            name='customizableuserflow',
            options={'verbose_name_plural': '          Customizable Userflows'},
        ),
        migrations.AlterModelOptions(
            name='debuglog',
            options={'verbose_name_plural': '    Auth2 Logs'},
        ),
        migrations.AlterModelOptions(
            name='identityprovider',
            options={'verbose_name_plural': '         Identity Providers'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'User', 'verbose_name_plural': '                Users'},
        ),
        migrations.AlterModelOptions(
            name='normalusertoken',
            options={'verbose_name': 'System User', 'verbose_name_plural': '               User Tokens'},
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'System User', 'verbose_name_plural': '              System Users'},
        ),
        migrations.AlterModelOptions(
            name='systemusertoken',
            options={'verbose_name': 'System User', 'verbose_name_plural': '             System User Tokens'},
        ),
        migrations.AlterModelOptions(
            name='trafficdata',
            options={'verbose_name_plural': '      Traffic Data'},
        ),
        migrations.AlterModelOptions(
            name='trafficreport',
            options={'verbose_name_plural': '     Traffic Report'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '              Users'},
        ),
        migrations.AlterModelOptions(
            name='userauthorization',
            options={'verbose_name_plural': '       User Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name_plural': '            User Groups'},
        ),
        migrations.AlterModelOptions(
            name='usergroupauthorization',
            options={'verbose_name_plural': '           User Group Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': '        Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='usertotp',
            options={'verbose_name_plural': '        User TOTPs'},
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='db_avg_time',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='db_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='redis_avg_time',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='redis_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='db_avg_time',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='db_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='redis_avg_time',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='redis_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
