# Generated by Django 4.2.16 on 2025-03-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0048_trafficcontrol_alter_debuglog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcontrol',
            name='exempt_groups',
            field=models.ManyToManyField(to='authome.usergroup'),
        ),
        migrations.AddField(
            model_name='trafficcontrol',
            name='exempt_include',
            field=models.BooleanField(default=True, help_text='Exempt the traffic control for the user groups which is include/exclude the exempt_groups'),
        ),
    ]
