# Generated by Django 4.2.16 on 2025-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0050_trafficcontrol_block_alter_debuglog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcontrol',
            name='block',
            field=models.BooleanField(default=False, help_text='If true, block the request until the running requests are less than the concurrency limit'),
        ),
    ]
