# Generated by Django 5.1.7 on 2025-05-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0051_alter_trafficcontrol_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth2cluster',
            options={'verbose_name_plural': '      Auth2 Clusters'},
        ),
        migrations.AlterModelOptions(
            name='debuglog',
            options={'verbose_name_plural': '   Auth2 Logs'},
        ),
        migrations.AlterModelOptions(
            name='trafficcontrol',
            options={'verbose_name_plural': '       Traffic Control'},
        ),
        migrations.AlterModelOptions(
            name='trafficdata',
            options={'verbose_name_plural': '     Traffic Data'},
        ),
        migrations.AlterModelOptions(
            name='trafficreport',
            options={'verbose_name_plural': '    Traffic Report'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userauthorization',
            options={'verbose_name_plural': 'User Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': 'Access Tokens'},
        ),
        migrations.AddField(
            model_name='trafficcontrol',
            name='timeout',
            field=models.PositiveIntegerField(help_text='The maximum seconds between the booking time and the current time.', null=True),
        ),
    ]
