# Generated by Django 5.1.7 on 2025-09-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0053_alter_userauthorization_excluded_paths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth2cluster',
            name='directconnect',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
